#!/bin/sh
set -e

DIR=/sftp-chroot

is_mnt()
{
  awk '$2~/^\/sftp-chroot$/' /proc/mounts | grep -q .
}

if ! is_mnt
then
  if [ ! -d "$DIR" ]
  then
    mkdir -m 0755 -p "$DIR"
  fi
  mount -o mode=755,uid=0,gid=0 -t tmpfs tmpfs "$DIR"
fi
