#!/usr/bin/perl -T -CSDAL

use warnings;
use strict;
use IServ::Valid;
use Stsbl::IServ::IO;
use Stsbl::IServ::Log;

undef %ENV;

my $m_ip = qr/^[0-9a-f.:]{1,64}$/;
my $m_action = qr/^(login|logout)$/;

my ($action, $ip, $act) = @ARGV;

die "usage: $0 action ip act" if not defined $action
    or not defined $ip or not defined $act;

IServ::Valid::User $act;
error "invalid ip" if not $ip =~ /$m_ip/;
error "invalid action" if not $action =~ /$m_action/;

my @pwnam = getpwnam $act;
my $fullname = $pwnam[6];

$Stsbl::IServ::Log::logip = $ip;
$Stsbl::IServ::Log::logname = $fullname;

if ($action eq "login")
{
  Stsbl::IServ::Log::log_store "SSH-Login erfolgreich";
}
elsif ($action eq "logout")
{
  Stsbl::IServ::Log::log_store "SSH-Logout erfolgreich";
}
