#!/usr/bin/perl -CSDAL

use warnings;
use strict;

my $fn_dirs = "/etc/iserv/sftp-chroot";
my $dest = "/sftp-chroot";

sub mount_failure($)
{
  my $mountpoint = shift;

  die "mount of $mountpoint in $dest failed!\n";
}

# mount tmpfs if /sftp-chroot is not a mountpoint
if (system ("mountpoint", "-q", $dest))
{
  print "mount tmpfs on $dest.\n";
  system ("umount", "-l", "-R", $dest) == 0 or die "umount of $dest failed!\n";
  system ("mount", "-o", "mode=755,uid=0,gid=0", "-t", "tmpfs", "tmpfs", "/sftp-chroot") == 0 or mount_failure "tmpfs";
}

open my $fh, "<", $fn_dirs;

my %want;
my %given;

while (<$fh>)
{
  chomp;

  # empty line
  next if /^$/;
  # comment
  next if /^#/;

  # allow only absolute paths
  die "invalid directory name: $_\n!" if not /^\//;

  print "adding mount $_ to chroot.\n";
  $want{$_} = 1;
}

close $fh;

open $fh, "<", "/proc/mounts";

while (<$fh>)
{
  chomp;
  next if not /^.*\s\/sftp-chroot(.*)\s(ext[0-9]|tmpfs|devtmpfs|sysfs|proc|devpts)/;
  my $mountpoint = $1;
  next if $mountpoint eq "" or not defined $mountpoint;

  print "mount $mountpoint given.\n";

  if (defined $want{$mountpoint})
  {
    print "mount $mountpoint is wanted, keep it.\n";
    $given{$mountpoint} = 1;
  } else
  {
    # ignore sub mounts in /run and /var/run
    next if $mountpoint =~ /^(\/run|\/var\/run)/;
    print "mount $mountpoint is not wanted, unmount it.\n";
    system ("umount", "-l", "-R", $dest . $mountpoint) == 0 or die "umount of " . $dest . $mountpoint . " failed!\n";
    rmdir $dest . $mountpoint;
  }
}

for (keys %want)
{
  next if defined $given{$_};
  
  die "invalid directory $_!" if not -e $_;

  print "bind not existing $_.\n";
  
  system ("mkdir", "-p", $dest . $_) == 0 or die "mkdir " . $_ . $dest . " failed!\n";

  # special handling for sys/proc/dev/pts
  if ($_ eq "/dev")
  {
    system ("mount", "-t", "devtmpfs", "udev", $dest . $_) == 0 or mount_failure $_;
  } elsif ($_ eq "/sys")
  {
    system ("mount", "-t", "sysfs", "sysfs", $dest . $_, "-o", "rw,nosuid,nodev,noexec,relatime") == 0 or mount_failure $_;
  } elsif ($_ eq "/proc")
  {
    system ("mount", "-t", "proc", "proc", $dest . $_, "-o", "rw,nosuid,nodev,noexec,relatime") == 0 or mount_failure $_;
  } elsif ($_ eq "/dev/pts")
  {
    system ("mount", "-t", "devpts", "devpts", $dest . $_) == 0 or mount_failure $_; 
  } else 
  {
    system ("mount", "--bind", $_, $dest . $_) == 0 or mount_failure $_;
  }
}
