services:
    _defaults:
        autoconfigure: true
        autowire: true
        public: false

    Stsbl\SftpBundle\:
        resource: '../../*'
        exclude: '../../{Entity,Model,Resources,Tests}'

    Stsbl\SftpBundle\Controller\:
        resource: '../../Controller/*'
        tags: ['controller.service_arguments']
